var structure = {
  lessons: [
    "How are you?",
    "When is your birthday?",
    "What do you like to do?",
    "Why do you like to shop?",
    "Who is in your family?",
    "Tell me about your family",
    "What is that?",
    "What are those?",
    "What do you do in the morning?",
    "What are you doing now?",
    "What time is it?",
    "How's the weather?",
    "What do you do for work?",
    "Tell me about your job",
    "What is your favorite food?",
    "What is that?",
    "Where do you like to eat?",
    "How much does this cost?",
    "Where do you live?",
    "I'm glad your visiting!",
    "Where are you going?",
    "My foot hurts",
    "I feel sick",
    "Review",
    "2 How are you?",
    "2 When is your birthday?",
    "2 What do you like to do?",
    "2 Why do you like to shop?",
    "2 Who is in your family?",
    "2 Tell me about your family",
    "2 What is that?",
    "2 What are those?",
    "2 What do you do in the morning?",
    "2 What are you doing now?",
    "2 What time is it?",
    "2 How's the weather?",
    "2 What do you do for work?",
    "2 Tell me about your job",
    "2 What is your favorite food?",
    "2 What is that?",
    "2 Where do you like to eat?",
    "2 How much does this cost?",
    "2 Where do you live?",
    "2 I'm glad your visiting!",
    "2 Where are you going?",
    "2 My foot hurts",
    "2 I feel sick",
    "2 Review",
  ],
  practices: ["Class Practice", "Extra Mile", "Stories"]
}

module.exports = structure;
